### ISSUE TITLE
Herbalism Skill Not Increasing with Wheat

### ISSUE THREAD

**Issue by hamcoremusic** [mcMMO-Dev/mcMMO#3226]
Hello!

I am having an issue with the latest build of McMMO (1.5.08). When planting and gathering wheat I do not receive any herbalism XP.

**Comment by Zefferis** [comment]
Yeah; same problem, it's being talked about (kinda) though.

https://github.com/mcMMO-Dev/mcMMO/issues/3207

**Comment by Angel9001** [comment]
all this crops that got added in 193# no longer give any xp to herbalism skill regardless of been fully grown or grow %. Tried altering the xp on this lines in the config file to see if they start giving xp but unfinished crop also don't give any xp. all other plants are unaffected. I'm running version 194# the problem consisted in this version

https://github.com/mcMMO-Dev/mcMMO/commit/44684fcfd0ef11bb2ed5c5681a1d80050db67a9e
this is the only commit i can see that might have altered something with herbalism

**Comment by runelynx** [comment]
Player reported this applies to potatoes :(

**Comment by Zefferis** [comment]
It applies to all crops except beetroot / grasses / flowers / mushrooms.

It effects blocks in a non chunk basis, slowly but eventually prevents all player crops (potatoes, carrots, wheat) from giving xp

**Comment by DiscoveriesMC** [comment]
Also experiencing this issue, tried adding "Wheat" to the experience config and still nothing. I didn't realize that they changed all crops to be under one value.

**Comment by kobini2** [comment]
Also experienced this issue, but I fixed the problem in a local version.

com\gmail\nossr50\skills\herbalism\HerbalismManager.java
line 128:
`if (oneBlockPlant && mcMMO.getPlaceStore().isTrue(blockState)) {`
to
`if (!oneBlockPlant && mcMMO.getPlaceStore().isTrue(blockState)) {`
That's the only thing I changed.

**Comment by Seeroh** [comment]
@kobini2 Care to share that .java file from the .jar (A little easier for me to check the code to see if anything was tampered with, so I can fix the issue on my server)

**Comment by kobini2** [comment]
It;s literaly 1 character but I'll pastebin it.

**Comment by Seeroh** [comment]
I meant posting the file. I'm not really adept with building jars. So the code is easy enough to have, but building it is the problem. I don't have any idea on how that all works.

**Comment by Sikatsu** [comment]
Same issue. Herbalism is broken, @t00thpick1

**Comment by kobini2** [comment]
I'll just leave my fixed version here:
https://mega.nz/#!fIhyzS5L!wIeF60nxzqpE7SFNxPu-xJc58TzXhLL04l4vWP0Jzt8

**Comment by Sikatsu** [comment]
Is that the latest source with the herbalism fix?

**Comment by kobini2** [comment]
The source can be 3 days old, I can always update it if you want.

**Comment by mibby** [comment]
Can confirm that this is an issue.

**Comment by t00thpick1** [comment]
Should be fixed.  will need to regen experience config, sorry.  I thought I could preserve backwards compat for config but I was wrong.

**Comment by Seeroh** [comment]
I just tried with the latest version, and a clean install, still having the problem.

**Comment by mibby** [comment]
@t00thpick1 Perhaps do the change @kobini2 made? As his build seemed to work fine with my players testing when I tested.

https://github.com/mcMMO-Dev/mcMMO/blob/24f8b2fbd5d4b12e5ad19dc598b3c1177eafaa4d/src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java#L128

Changing 
```
if (oneBlockPlant && mcMMO.getPlaceStore().isTrue(blockState)) {
```

to

```
if (!oneBlockPlant && mcMMO.getPlaceStore().isTrue(blockState)) {
```

**Comment by Seeroh** [comment]
@kobini2 @mibby @Sikatsu @Zefferis 

In case it has not been found, or reported, there seems to be an issue with herbalism (at the very least) with your fixed mcMMO where you can place down flowers, and immediately break them for xp, and likely extra drops. Basically a grind and dupe glitch. Might want to look into it.

**Comment by SXRWahrheit** [comment]
@t00thpick1 Is it possible for you to list the changes so we can manually patch our configs rather than losing all our edits? I can do a compare, I guess, but yeah

**Comment by runelynx** [comment]
You can see that in github

**Comment by SXRWahrheit** [comment]
It looks like I only got these changes:
```
#  Last updated on 1.5.08-SNAPSHOT-b${BUILD_NUMBER}
```
```
        Stone|*: 30
        Stained_Clay|*: 50
```

**Comment by SXRWahrheit** [comment]
Users also report no EXP gain on version 195, @t00thpick1.

**Comment by kobini2** [comment]
I updated my version to the lastest dev-build, and it should also fix the bug @Seeroh mentioned.

https://mega.nz/#!fIhyzS5L!wIeF60nxzqpE7SFNxPu-xJc58TzXhLL04l4vWP0Jzt8

Changes:
com\gmail\nossr50\skills\herbalism\HerbalismManager.java > https://pastebin.com/XjFbQy5w

**Comment by SXRWahrheit** [comment]
@kobini2 Your link appears to be invalid - file was removed. I appreciate the effort, though!

**Comment by kobini2** [comment]
Thanks for pointing it out @SXRWahrheit . 2 links, for safety (for some odd reason the previous was removed).

https://mega.nz/#!2ZgUmLiZ!v_Nxo9JXS3IYhpF8QQB1b4Z5ULTzDs8jP36wVlFIADc
https://drive.google.com/open?id=0B18fJQbDg1Vsdk95WDUwa0ZWZ0k

**Comment by malaeus** [comment]
can confirm latest dev build does not allow players to gain xp from crops planted by a player. HOWEVER if the crops are placed using worldedit, the players gain xp with no problem

**Comment by Sikatsu** [comment]
@kobini2 Using that version players still report they are able to place flowers and remove them to earn XP in herbalism and receive double drops. So the dupe is still possible it seems. Running (Herbalism fix v2)

**Comment by kobini2** [comment]
My players also found a bug, lily pads keep giving xp

Herbalism fix v3:
https://drive.google.com/drive/folders/0B18fJQbDg1VsVVo1Y290OVhBaW8?usp=sharing
https://mega.nz/#!TQYXWCCK!XoTolDT-Ee4HU-nI1lu1UF05ihfxD5vrCYvWXTCnprY

**Comment by t00thpick1** [comment]
Would recommend reading:  https://github.com/mcMMO-Dev/mcMMO/commit/f1ac5739e4681fb3e14849baf3738a0df97a3a95

Kobini's "fix" not recommended due to it just ignoring the block tracking systems in place to prevent exp exploitation.  Although the effort is appreciated.

**Comment by kobini2** [comment]
While it may not be the best fix, it is only temporary until your version works again.

**Comment by kobini2** [comment]
Can confirm, completely fixed.

**Comment by BurntValentine** [comment]
The updated dev build hasn't fixed it for me - updated mcmmo jar and regenerated the experience.yml file on restart but any crops I place still don't give me any experience, only crops placed by others

**Comment by SXRWahrheit** [comment]
Running 196 with this experience.yml and no exp gain:

```
    Herbalism:
        Allium: 300
        Azure_Bluet: 150
        Beetroot_Block_Ripe: 50
        Blue_Orchid: 150
        Brown_Mushroom: 150
        Cactus: 30
        Carrot_Ripe: 50
        Chorus_Flower: 25
        Chorus_Plant: 1
        Cocoa_Ripe: 30
        Crops_Ripe: 50
        Dead_Bush: 30
        Lilac: 50
        Melon_Block: 20
        Nether_Warts_Ripe: 50
        Orange_Tulip: 150
        Oxeye_Daisy: 150
        Peony: 50
        Pink_Tulip: 150
        Poppy: 100
        Potato_Ripe: 50
        Pumpkin: 20
        Red_Mushroom: 150
        Red_Tulip: 150
        Rose_Bush: 50
        Small_Fern: 10
        Small_Grass: 10
        Sugar_Cane_Block: 30
        Sunflower: 50
        Tall_Grass: 50
        Tall_Fern: 50
        Vine: 10
        Water_Lily: 100
        White_Tulip: 150
        Yellow_Flower: 100
```

**Comment by Sikatsu** [comment]
Same issue, regenerated my experience config but I still have that problem. Back to @kobini2 build for now.

**Comment by BurntValentine** [comment]
Correction:: Does work, but any crops that had already been placed won't work. Planting new crops and leaving them to grow before harvesting worked fine on dev build 196

**Comment by SXRWahrheit** [comment]
Will it not work with bonemeal, then? Because that's what I tried, and no dice.

**Comment by Sikatsu** [comment]
Bonemeal doesn't work I guess.

**Comment by SXRWahrheit** [comment]
Can we get a fix for bonemeal @t00thpick1?

**Comment by iSkeptical** [comment]
I'm using latest mcmmo build.
Regenerated experience yml file.
Still not gaining any Hebalism exp from crops.

**Comment by nathanprocks** [comment]
@iSkeptical It works for me. Did you replant the crops without using bonemeal?

**Comment by Zefferis** [comment]
Perhaps you should go into:
/<world>/

find your mcmmo_regions folder for your 3 worlds and delete it and restart the world?

Might be a lingering effect on your actual region files
