### ISSUE TITLE
Between build 47 and 49 Herbalism broke for carrots, potatoes, and wheat

### ISSUE THREAD

**Issue by Momshroom** [mcMMO-Dev/mcMMO#3599]
If you really need me to supply all the configs, etc, I can, but I haven't changed anything except for updating from build 47 to 49. 
That update fixed an issue I was having with gold ore not giving double drops with mining, but completely broke carrots, potatoes, beetroot, cocoa, and wheat for herbalism.  Cane still works.
By broke I mean: no replant, no xp, and green terra doesn't activate on them.

I'm on Spigot 1.13.1

Here's the herbalism section from my experience.yml: (but I didn't change anything between it working and it not working)
    Herbalism:
        Allium: 300
        Azure_Bluet: 150
        Beetroots_Ripe: 50
        Blue_Orchid: 150
        Brown_Mushroom: 150
        Cactus: 30
        Carrots_Ripe: 50
        Chorus_Flower: 25
        Chorus_Plant: 1
        Cocoa_Ripe: 30
        Wheat_Ripe: 50
        Dead_Bush: 30
        Lilac: 50
        Melon: 20
        Nether_Wart_Ripe: 50
        Orange_Tulip: 150
        Oxeye_Daisy: 150
        Peony: 50
        Pink_Tulip: 150
        Poppy: 100
        Potatoes_Ripe: 50
        Pumpkin: 20
        Red_Mushroom: 150
        Red_Tulip: 150
        Rose_Bush: 50
        Fern: 10
        Grass: 10
        Sugar_Cane: 30
        Sunflower: 50
        Tall_Grass: 50
        Large_Fern: 50
        Vine: 10
        Lily_Pad: 100
        White_Tulip: 150
        Dandelion: 100

The herbalism section from the config.yml for double drops:
Double_Drops:
    Herbalism:
        Beetroots_Ripe: true
        Brown_Mushroom: true
        Cactus: true
        Carrots_Ripe: true
        Cocoa_Ripe: true
        Wheat_Ripe: true
        Melon: true
        Nether_Wart_Ripe: true
        Potatoes_Ripe: true
        Pumpkin: true
        Red_Mushroom: true
        Red_Tulip: true
        Sugar_Cane: true
        Vine: true
        Lily_Pad: true
        Dandelion: true

**Comment by t00thpick1** [comment]
Sorry about that, should be fixed.

**Comment by Momshroom** [comment]
I've only tested with carrots so far, but: they now replant properly and green terra activates on them, but they still do not give herbalism xp.
