### ISSUE TITLE
Bone Meal incorrectly marking Azalea trees as unnatural

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4640]
Woodcutting xp doesnt increase when chopping down Azalea trees.
Tree Feller Doesnt work on Azalea Trees as well.

**Comment by andrewkm** [comment]
Noting down from our Discord convo so it doesn't get lost.
Looks like Azalea being sapling'ed is considered unnatural, while other saplings are all considered natural.

**Comment by Greymagic27** [comment]
Looks like https://github.com/mcMMO-Dev/mcMMO/commit/c30892a0a56edaa1fc541b439ee1031bb8e10789 might have fixed this or solved at least part of the issue?

**Comment by andrewkm** [comment]
It did not solve bone mealed Azalea trees bein GB detected as non natural. @nossr50 is aware via Discord.
