### ISSUE TITLE
Issue #5052 still present and affects additional blocks

### ISSUE THREAD

**Issue by 777555777** [mcMMO-Dev/mcMMO#5064]
The issue described in #5052 wasn't fixed as the proclaimed fix checks the blocks effected by double-/triple-drop which spawners etc aren't. There also already existed a method to filter out unwanted drops from blast mining which the fix could expand upon (`isDropIllegal`).

Additionally there are more blocks affected which aren't obtainable normally.
These include:
- spawner
- chorus_plant
- dirt_path
- farmland
- infested_cobblestone
- infested_stone
- infested_deepslate
- infested_stone_bricks
- infested_mossy_stone_bricks
- infested_cracked_stone_bricks
- infested_chiseled_stone_bricks

As well as some blocks otherways obtainable, but not obtainable by breaking them:
- suspicious_sand
- suspicious_gravel
- tall_grass
- large_fern

**The list might not be complete**, so checking if the block is normally obtainable by breaking it using silktouch might be a better solution.

Additionally, it seems to make a difference if the block is created by the player (e.g., using a hoe to create farmland) or not. Blocks created by the player do not drop, while naturally generated blocks do drop. This also affects normal blocks placed by players which might be confusing to users.

Furthermore non mining blocks only have a 50% chance to drop while normal tnt has had a 100% chance to drop items since 1.14. Changing the chance to 100% would better align with vanilla tnt behaviour.

**Comment by nossr50** [comment]
Thanks for the report, will look into it.

**Comment by RasmusKD** [comment]
fixed in https://github.com/mcMMO-Dev/mcMMO/pull/5068

**Comment by 777555777** [comment]
I just build from source and for spawners etc the issue still persists.
And may I ask why the dropchance of non ore blocks was lowered even further to 10% while vanilla has a 100% dropchance? As non ore blocks don't benefit from the yield bonus there shouldn't be a risk of item duplication.

**Comment by nossr50** [comment]
> I just build from source and for spawners etc the issue still persists. And may I ask why the dropchance of non ore blocks was lowered even further to 10% while vanilla has a 100% dropchance? As non ore blocks don't benefit from the yield bonus there shouldn't be a risk of item duplication.

Thank you for pointing this out, BlastMining is in need of a rework for how it drops things, but I may be able to patch this in for now.

**Comment by nossr50** [comment]
> I just build from source and for spawners etc the issue still persists.
It should be impossible for them to drop, but I'll go double check over everything
