### ISSUE TITLE
Folia errors "Accessing entity state off owning region's thread"

### ISSUE THREAD

**Issue by iLemon** [mcMMO-Dev/mcMMO#5099]
https://pastes.dev/PXQDyhAbda

```
[02:16:36] [Region Scheduler Thread #0/ERROR]: Could not pass event EntityDeathEvent to mcMMO v2.2.022
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEnderman.getHandle(CraftEnderman.java:74) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEnderman.getHandle(CraftEnderman.java:15) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.equals(CraftEntity.java:567) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at java.util.WeakHashMap.matchesKey(WeakHashMap.java:298) ~[?:?]
	at java.util.WeakHashMap.getEntry(WeakHashMap.java:442) ~[?:?]
	at java.util.WeakHashMap.containsKey(WeakHashMap.java:429) ~[?:?]
	at com.gmail.nossr50.util.MobMetadataUtils.removeMobFlag(MobMetadataUtils.java:155) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.MobMetadataUtils.removeMobFlags(MobMetadataUtils.java:172) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.TransientMetadataTools.cleanLivingEntityMetadata(TransientMetadataTools.java:35) ~[mcMMO.jar:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDeathLowest(EntityListener.java:671) ~[mcMMO.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor501.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at ltd.lemongaming.mobstacker.listeners.ListenerCommon.onEntityDamageEvent(ListenerCommon.java:135) ~[LGMobStacker-3.1.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor536.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:267) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1188) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1178) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1081) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1237) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1499) ~[?:?]
	at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:417) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:2089) ~[?:?]
	at net.minecraft.world.level.block.Block.fallOn(Block.java:468) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1795) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:396) ~[?:?]
	at net.minecraft.world.entity.Entity.move(Entity.java:1171) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2977) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2911) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3493) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:696) ~[?:?]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
	at net.minecraft.world.entity.monster.EnderMan.aiStep(EnderMan.java:287) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3085) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:458) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1564) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1369) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:1017) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:620) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:996) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1822) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1661) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:417) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:16:36] [Region Scheduler Thread #0/ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEnderman.getHandle(CraftEnderman.java:74) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEnderman.getHandle(CraftEnderman.java:15) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.equals(CraftEntity.java:567) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at java.util.WeakHashMap.matchesKey(WeakHashMap.java:298) ~[?:?]
	at java.util.WeakHashMap.getEntry(WeakHashMap.java:442) ~[?:?]
	at java.util.WeakHashMap.containsKey(WeakHashMap.java:429) ~[?:?]
	at com.gmail.nossr50.util.MobMetadataUtils.removeMobFlag(MobMetadataUtils.java:155) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.MobMetadataUtils.removeMobFlags(MobMetadataUtils.java:172) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.TransientMetadataTools.cleanLivingEntityMetadata(TransientMetadataTools.java:35) ~[mcMMO.jar:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDeathLowest(EntityListener.java:671) ~[mcMMO.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor501.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at ltd.lemongaming.mobstacker.listeners.ListenerCommon.onEntityDamageEvent(ListenerCommon.java:135) ~[LGMobStacker-3.1.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor536.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[citrus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:267) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1188) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1178) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1081) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1237) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1499) ~[?:?]
	at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:417) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:2089) ~[?:?]
	at net.minecraft.world.level.block.Block.fallOn(Block.java:468) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1795) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:396) ~[?:?]
	at net.minecraft.world.entity.Entity.move(Entity.java:1171) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2977) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2911) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3493) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:696) ~[?:?]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
	at net.minecraft.world.entity.monster.EnderMan.aiStep(EnderMan.java:287) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3085) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:458) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1564) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1369) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:1017) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:620) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:996) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1822) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1661) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:417) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[citrus-1.20.4.jar:git-Citrus-"da0c45b"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by nossr50** [comment]
Should be fixed, will be in the next patch

**Comment by nossr50** [comment]
I'm not 100% sure if I fixed this one, please try out the next mcMMO patch (2.2.027) when it drops and let me know if you still run into this issue, if you do, feel free to reopen this ticket.

**Comment by iLemon** [comment]
https://pastes.dev/uni2K58qb9 still getting this one on 2.2.028

```
[16:18:40] [Region Scheduler Thread #10/ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread Region Scheduler Thread #10 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:58) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftWarden.getHandle(CraftWarden.java:27) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftWarden.getHandle(CraftWarden.java:12) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftEntity.isInWorld(CraftEntity.java:947) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftEntity.isValid(CraftEntity.java:401) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at mcMMO.jar/com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:72) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.mcmmo.folialib.impl.FoliaImplementation.lambda$runAtEntityTimer$21(FoliaImplementation.java:342) ~[mcMMO.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[citrus-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[citrus-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1714) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:416) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[16:18:40] [Region Scheduler Thread #10/WARN]: [mcMMO] Entity task for mcMMO v2.2.028 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:59) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftWarden.getHandle(CraftWarden.java:27) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftWarden.getHandle(CraftWarden.java:12) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftEntity.isInWorld(CraftEntity.java:947) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at org.bukkit.craftbukkit.entity.CraftEntity.isValid(CraftEntity.java:401) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at mcMMO.jar/com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:72) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.mcmmo.folialib.impl.FoliaImplementation.lambda$runAtEntityTimer$21(FoliaImplementation.java:342) ~[mcMMO.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[citrus-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[citrus-1.21.1.jar:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1714) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:416) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[citrus-1.21.1.jar:1.21.1-DEV-b9a4e22]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```
